# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170331_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='original',
            field=models.BooleanField(default=True, verbose_name='Is file original'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='repository', verbose_name='file instance'),
        ),
    ]
