# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170401_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.TextField(editable=False, unique=True, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='original',
            field=models.BooleanField(default=True, verbose_name='is file original'),
        ),
    ]
